name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install Poetry
        uses: abatilo/actions-poetry@v3
        with:
          poetry-version: 1.8.2

      - name: Configure Poetry and Install Dependencies
        run: |
          poetry config virtualenvs.create false
          poetry install --no-interaction --no-root --with dev

      - name: Run pre-commit checks
        run: pre-commit run --all-files
      
      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$PWD" >> $GITHUB_ENV
      
      - name: Run tests
        run: pytest --maxfail=1 --disable-warnings
        env:
          PYTHONPATH: services:src
          MLFLOW_TRACKING_URI: dummy
          CI: true

      - name: Log in to Docker Hub
        if: success() && github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & Push Airflow Image
        if: success() && github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v5
        with:
          context: ./services/airflow
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/airflow:latest

      - name: Build & Push MLflow Image
        if: success() && github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v5
        with:
          context: ./services/mlflow
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/mlflow:latest

      - name: Build & Push Streamlit Image
        if: success() && github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v5
        with:
          context: ./services/streamlit
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/streamlit:latest

      - name: Azure Login
        if: success() && github.ref == 'refs/heads/main'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        if: success() && github.ref == 'refs/heads/main'
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
          slot-name: 'production'
          images: ${{ secrets.DOCKERHUB_USERNAME }}/streamlit:latest
  
